# Generated by Django 5.2.4 on 2025-07-15 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_administator_delete_cupon_employee_checked_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
            ],
            options={
                'verbose_name': 'Ish jadvali',
                'verbose_name_plural': 'Ish jadvali',
            },
        ),
        migrations.AlterModelOptions(
            name='administator',
            options={'verbose_name': 'Administrator', 'verbose_name_plural': 'Administratorlar'},
        ),
        migrations.AlterModelOptions(
            name='attendance',
            options={'verbose_name': 'Kirish Chiqishlar', 'verbose_name_plural': 'Kirish Chiqishlar'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Xodim', 'verbose_name_plural': 'Xodimlar'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': 'Manzil', 'verbose_name_plural': 'Manzillar'},
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='employee',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='work_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='backend.workschedule'),
        ),
    ]
