# Generated by Django 5.2.4 on 2025-07-16 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_workschedule_alter_administator_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weekday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'Hafta kuni',
                'verbose_name_plural': 'Hafta kunlari',
            },
        ),
        migrations.RemoveField(
            model_name='employee',
            name='work_schedule',
        ),
        migrations.AddField(
            model_name='workschedule',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_schedules', to='backend.administator'),
        ),
        migrations.AddField(
            model_name='workschedule',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_schedules', to='backend.employee'),
        ),
        migrations.AddField(
            model_name='workschedule',
            name='weekday',
            field=models.ManyToManyField(related_name='work_schedules', to='backend.weekday'),
        ),
    ]
