# Generated by Django 5.2.4 on 2025-07-16 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_weekday_remove_employee_work_schedule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weekday',
            name='name_en',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
